/*
 * Copyright LWJGL. All rights reserved.
 * License terms: http://lwjgl.org/license.php
 * MACHINE GENERATED FILE, DO NOT EDIT
 */
package org.lwjgl.system;

/**
 * This class contains native methods that can be used to call dynamically loaded functions. It is used internally by the LWJGL bindings, but can also be used
 * to call other dynamically loaded functions. Not all possible signatures are available, only those needed by the LWJGL bindings. To call a function that does
 * not have a matching JNI method, {@link org.lwjgl.system.libffi.LibFFI LibFFI} can used.
 *
 * <p>All JNI methods in this class take an extra parameter, called {@code __functionAddress}. This must be a valid pointer to a native function with a
 * matching signature. The C language does not support method overloading, so each method has a postfix that matches the
 * <a href="http://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/types.html#type_signatures">JNI type signature</a> it supports. Only the primitive
 * type signatures are used, plus a 'P' type that corresponds to a pointer value. Pointer values are mapped to Java longs, but are properly converted in native
 * code on 32bit architectures.</p>
 */
public final class JNI {

	private JNI() {}

	public static native void invokeBBBBV(long __functionAddress, byte param0, byte param1, byte param2, byte param3);
	public static native void invokeBBBV(long __functionAddress, byte param0, byte param1, byte param2);
	public static native void invokeBV(long __functionAddress, byte param0);
	public static native void invokeDDDDDDV(long __functionAddress, double param0, double param1, double param2, double param3, double param4, double param5);
	public static native void invokeDDDDV(long __functionAddress, double param0, double param1, double param2, double param3);
	public static native void invokeDDDV(long __functionAddress, double param0, double param1, double param2);
	public static native void invokeDDV(long __functionAddress, double param0, double param1);
	public static native void invokeDV(long __functionAddress, double param0);
	public static native void invokeFFFFFFFFV(long __functionAddress, float param0, float param1, float param2, float param3, float param4, float param5, float param6, float param7);
	public static native void invokeFFFFV(long __functionAddress, float param0, float param1, float param2, float param3);
	public static native void invokeFFFV(long __functionAddress, float param0, float param1, float param2);
	public static native void invokeFFV(long __functionAddress, float param0, float param1);
	public static native void invokeFV(long __functionAddress, float param0);
	public static native void invokeFZV(long __functionAddress, float param0, boolean param1);
	public static native int invokeI(long __functionAddress);
	public static native void invokeIBBBBV(long __functionAddress, int param0, byte param1, byte param2, byte param3, byte param4);
	public static native double invokeID(long __functionAddress, int param0);
	public static native void invokeIDDDDDDV(long __functionAddress, int param0, double param1, double param2, double param3, double param4, double param5, double param6);
	public static native void invokeIDDDDV(long __functionAddress, int param0, double param1, double param2, double param3, double param4);
	public static native void invokeIDDDV(long __functionAddress, int param0, double param1, double param2, double param3);
	public static native void invokeIDDIDDV(long __functionAddress, int param0, double param1, double param2, int param3, double param4, double param5);
	public static native void invokeIDDIIDDIIPV(long __functionAddress, int param0, double param1, double param2, int param3, int param4, double param5, double param6, int param7, int param8, long param9);
	public static native void invokeIDDIIPV(long __functionAddress, int param0, double param1, double param2, int param3, int param4, long param5);
	public static native void invokeIDDV(long __functionAddress, int param0, double param1, double param2);
	public static native void invokeIDV(long __functionAddress, int param0, double param1);
	public static native float invokeIF(long __functionAddress, int param0);
	public static native void invokeIFFFFV(long __functionAddress, int param0, float param1, float param2, float param3, float param4);
	public static native long invokeIFFFP(long __functionAddress, int param0, float param1, float param2, float param3);
	public static native void invokeIFFFV(long __functionAddress, int param0, float param1, float param2, float param3);
	public static native void invokeIFFIFFV(long __functionAddress, int param0, float param1, float param2, int param3, float param4, float param5);
	public static native void invokeIFFIIFFIIPV(long __functionAddress, int param0, float param1, float param2, int param3, int param4, float param5, float param6, int param7, int param8, long param9);
	public static native void invokeIFFIIPV(long __functionAddress, int param0, float param1, float param2, int param3, int param4, long param5);
	public static native void invokeIFFV(long __functionAddress, int param0, float param1, float param2);
	public static native boolean invokeIFFZ(long __functionAddress, int param0, float param1, float param2);
	public static native void invokeIFV(long __functionAddress, int param0, float param1);
	public static native int invokeII(long __functionAddress, int param0);
	public static native void invokeIIDDDDV(long __functionAddress, int param0, int param1, double param2, double param3, double param4, double param5);
	public static native void invokeIIDDDV(long __functionAddress, int param0, int param1, double param2, double param3, double param4);
	public static native void invokeIIDDV(long __functionAddress, int param0, int param1, double param2, double param3);
	public static native void invokeIIDV(long __functionAddress, int param0, int param1, double param2);
	public static native void invokeIIFFFFFFFFFV(long __functionAddress, int param0, int param1, float param2, float param3, float param4, float param5, float param6, float param7, float param8, float param9, float param10);
	public static native void invokeIIFFFFPV(long __functionAddress, int param0, int param1, float param2, float param3, float param4, float param5, long param6);
	public static native void invokeIIFFFFV(long __functionAddress, int param0, int param1, float param2, float param3, float param4, float param5);
	public static native void invokeIIFFFV(long __functionAddress, int param0, int param1, float param2, float param3, float param4);
	public static native void invokeIIFFV(long __functionAddress, int param0, int param1, float param2, float param3);
	public static native boolean invokeIIFFZ(long __functionAddress, int param0, int param1, float param2, float param3);
	public static native void invokeIIFIV(long __functionAddress, int param0, int param1, float param2, int param3);
	public static native void invokeIIFV(long __functionAddress, int param0, int param1, float param2);
	public static native int invokeIII(long __functionAddress, int param0, int param1);
	public static native void invokeIIIDDDDV(long __functionAddress, int param0, int param1, int param2, double param3, double param4, double param5, double param6);
	public static native void invokeIIIDV(long __functionAddress, int param0, int param1, int param2, double param3);
	public static native float invokeIIIF(long __functionAddress, int param0, int param1, int param2);
	public static native void invokeIIIFFFFV(long __functionAddress, int param0, int param1, int param2, float param3, float param4, float param5, float param6);
	public static native boolean invokeIIIFPPPPZ(long __functionAddress, int param0, int param1, int param2, float param3, long param4, long param5, long param6, long param7);
	public static native void invokeIIIFV(long __functionAddress, int param0, int param1, int param2, float param3);
	public static native void invokeIIIIIIIIIIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, int param9, int param10, int param11, int param12, int param13, int param14);
	public static native void invokeIIIIIIIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, int param9, int param10, int param11);
	public static native void invokeIIIIIIIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, int param9, int param10, long param11);
	public static native void invokeIIIIIIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, int param9, long param10);
	public static native void invokeIIIIIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, int param9);
	public static native void invokeIIIIIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, long param9);
	public static native void invokeIIIIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8);
	public static native void invokeIIIIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, long param8);
	public static native void invokeIIIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7);
	public static native void invokeIIIIIIIIZV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, boolean param8);
	public static native void invokeIIIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, long param7);
	public static native void invokeIIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6);
	public static native void invokeIIIIIIIZV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, int param6, boolean param7);
	public static native void invokeIIIIIIPPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, long param6, long param7);
	public static native void invokeIIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, long param6);
	public static native void invokeIIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5);
	public static native void invokeIIIIIIZV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, int param5, boolean param6);
	public static native void invokeIIIIIPIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, long param5, int param6);
	public static native void invokeIIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, long param5);
	public static native void invokeIIIIIV(long __functionAddress, int param0, int param1, int param2, int param3, int param4);
	public static native void invokeIIIIIZIPV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, boolean param5, int param6, long param7);
	public static native void invokeIIIIIZV(long __functionAddress, int param0, int param1, int param2, int param3, int param4, boolean param5);
	public static native int invokeIIIIPI(long __functionAddress, int param0, int param1, int param2, int param3, long param4);
	public static native void invokeIIIIPIIPV(long __functionAddress, int param0, int param1, int param2, int param3, long param4, int param5, int param6, long param7);
	public static native void invokeIIIIPIPPV(long __functionAddress, int param0, int param1, int param2, int param3, long param4, int param5, long param6, long param7);
	public static native void invokeIIIIPPV(long __functionAddress, int param0, int param1, int param2, int param3, long param4, long param5);
	public static native void invokeIIIIPV(long __functionAddress, int param0, int param1, int param2, int param3, long param4);
	public static native void invokeIIIIPZV(long __functionAddress, int param0, int param1, int param2, int param3, long param4, boolean param5);
	public static native void invokeIIIIV(long __functionAddress, int param0, int param1, int param2, int param3);
	public static native void invokeIIIIZIV(long __functionAddress, int param0, int param1, int param2, int param3, boolean param4, int param5);
	public static native void invokeIIIPIFFIPV(long __functionAddress, int param0, int param1, int param2, long param3, int param4, float param5, float param6, int param7, long param8);
	public static native void invokeIIIPIIIV(long __functionAddress, int param0, int param1, int param2, long param3, int param4, int param5, int param6);
	public static native void invokeIIIPIIPV(long __functionAddress, int param0, int param1, int param2, long param3, int param4, int param5, long param6);
	public static native void invokeIIIPIIV(long __functionAddress, int param0, int param1, int param2, long param3, int param4, int param5);
	public static native void invokeIIIPIPPPPPPV(long __functionAddress, int param0, int param1, int param2, long param3, int param4, long param5, long param6, long param7, long param8, long param9, long param10);
	public static native void invokeIIIPIV(long __functionAddress, int param0, int param1, int param2, long param3, int param4);
	public static native long invokeIIIPPP(long __functionAddress, int param0, int param1, int param2, long param3, long param4);
	public static native void invokeIIIPPPPV(long __functionAddress, int param0, int param1, int param2, long param3, long param4, long param5, long param6);
	public static native void invokeIIIPPPV(long __functionAddress, int param0, int param1, int param2, long param3, long param4, long param5);
	public static native void invokeIIIPPV(long __functionAddress, int param0, int param1, int param2, long param3, long param4);
	public static native void invokeIIIPV(long __functionAddress, int param0, int param1, int param2, long param3);
	public static native void invokeIIIPZV(long __functionAddress, int param0, int param1, int param2, long param3, boolean param4);
	public static native void invokeIIIV(long __functionAddress, int param0, int param1, int param2);
	public static native void invokeIIIZIIIV(long __functionAddress, int param0, int param1, int param2, boolean param3, int param4, int param5, int param6);
	public static native void invokeIIIZIPV(long __functionAddress, int param0, int param1, int param2, boolean param3, int param4, long param5);
	public static native void invokeIIIZIV(long __functionAddress, int param0, int param1, int param2, boolean param3, int param4);
	public static native void invokeIIIZPV(long __functionAddress, int param0, int param1, int param2, boolean param3, long param4);
	public static native void invokeIIIZV(long __functionAddress, int param0, int param1, int param2, boolean param3);
	public static native long invokeIIJ(long __functionAddress, int param0, int param1);
	public static native void invokeIIJJJJV(long __functionAddress, int param0, int param1, long param2, long param3, long param4, long param5);
	public static native void invokeIIJJJV(long __functionAddress, int param0, int param1, long param2, long param3, long param4);
	public static native void invokeIIJJV(long __functionAddress, int param0, int param1, long param2, long param3);
	public static native void invokeIIJPV(long __functionAddress, int param0, int param1, long param2, long param3);
	public static native void invokeIIJV(long __functionAddress, int param0, int param1, long param2);
	public static native long invokeIIP(long __functionAddress, int param0, int param1);
	public static native int invokeIIPI(long __functionAddress, int param0, int param1, long param2);
	public static native int invokeIIPIIIIFI(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, int param6, float param7);
	public static native void invokeIIPIIIIIFV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, int param6, int param7, float param8);
	public static native void invokeIIPIIIIIPV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, int param6, int param7, long param8);
	public static native void invokeIIPIIIIPV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, int param6, long param7);
	public static native void invokeIIPIIIIV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, int param6);
	public static native void invokeIIPIIIPIIFV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, long param6, int param7, int param8, float param9);
	public static native void invokeIIPIIIPV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5, long param6);
	public static native void invokeIIPIIIV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, int param5);
	public static native void invokeIIPIIPV(long __functionAddress, int param0, int param1, long param2, int param3, int param4, long param5);
	public static native void invokeIIPIIV(long __functionAddress, int param0, int param1, long param2, int param3, int param4);
	public static native void invokeIIPIPV(long __functionAddress, int param0, int param1, long param2, int param3, long param4);
	public static native void invokeIIPIV(long __functionAddress, int param0, int param1, long param2, int param3);
	public static native int invokeIIPPIIIIFI(long __functionAddress, int param0, int param1, long param2, long param3, int param4, int param5, int param6, int param7, float param8);
	public static native void invokeIIPPIIIV(long __functionAddress, int param0, int param1, long param2, long param3, int param4, int param5, int param6);
	public static native void invokeIIPPIIPV(long __functionAddress, int param0, int param1, long param2, long param3, int param4, int param5, long param6);
	public static native void invokeIIPPIIV(long __functionAddress, int param0, int param1, long param2, long param3, int param4, int param5);
	public static native void invokeIIPPIV(long __functionAddress, int param0, int param1, long param2, long param3, int param4);
	public static native void invokeIIPPPPIV(long __functionAddress, int param0, int param1, long param2, long param3, long param4, long param5, int param6);
	public static native int invokeIIPPPPPI(long __functionAddress, int param0, int param1, long param2, long param3, long param4, long param5, long param6);
	public static native int invokeIIPPPPPPI(long __functionAddress, int param0, int param1, long param2, long param3, long param4, long param5, long param6, long param7);
	public static native void invokeIIPPPPPV(long __functionAddress, int param0, int param1, long param2, long param3, long param4, long param5, long param6);
	public static native void invokeIIPPPV(long __functionAddress, int param0, int param1, long param2, long param3, long param4);
	public static native void invokeIIPPV(long __functionAddress, int param0, int param1, long param2, long param3);
	public static native void invokeIIPV(long __functionAddress, int param0, int param1, long param2);
	public static native void invokeIIV(long __functionAddress, int param0, int param1);
	public static native boolean invokeIIZ(long __functionAddress, int param0, int param1);
	public static native long invokeIIZIIJ(long __functionAddress, int param0, int param1, boolean param2, int param3, int param4);
	public static native void invokeIIZIV(long __functionAddress, int param0, int param1, boolean param2, int param3);
	public static native void invokeIIZPV(long __functionAddress, int param0, int param1, boolean param2, long param3);
	public static native void invokeIIZV(long __functionAddress, int param0, int param1, boolean param2);
	public static native long invokeIJ(long __functionAddress, int param0);
	public static native void invokeIJJJJV(long __functionAddress, int param0, long param1, long param2, long param3, long param4);
	public static native void invokeIJJJV(long __functionAddress, int param0, long param1, long param2, long param3);
	public static native void invokeIJJV(long __functionAddress, int param0, long param1, long param2);
	public static native void invokeIJV(long __functionAddress, int param0, long param1);
	public static native long invokeIP(long __functionAddress, int param0);
	public static native int invokeIPI(long __functionAddress, int param0, long param1);
	public static native int invokeIPIIFII(long __functionAddress, int param0, long param1, int param2, int param3, float param4, int param5);
	public static native void invokeIPIIIV(long __functionAddress, int param0, long param1, int param2, int param3, int param4);
	public static native void invokeIPIIV(long __functionAddress, int param0, long param1, int param2, int param3);
	public static native long invokeIPIP(long __functionAddress, int param0, long param1, int param2);
	public static native void invokeIPIPIPV(long __functionAddress, int param0, long param1, int param2, long param3, int param4, long param5);
	public static native void invokeIPIPIV(long __functionAddress, int param0, long param1, int param2, long param3, int param4);
	public static native void invokeIPIPPV(long __functionAddress, int param0, long param1, int param2, long param3, long param4);
	public static native void invokeIPIPV(long __functionAddress, int param0, long param1, int param2, long param3);
	public static native void invokeIPIV(long __functionAddress, int param0, long param1, int param2);
	public static native long invokeIPP(long __functionAddress, int param0, long param1);
	public static native int invokeIPPI(long __functionAddress, int param0, long param1, long param2);
	public static native void invokeIPPIIIV(long __functionAddress, int param0, long param1, long param2, int param3, int param4, int param5);
	public static native void invokeIPPIIV(long __functionAddress, int param0, long param1, long param2, int param3, int param4);
	public static native long invokeIPPIP(long __functionAddress, int param0, long param1, long param2, int param3);
	public static native void invokeIPPIPV(long __functionAddress, int param0, long param1, long param2, int param3, long param4);
	public static native void invokeIPPIV(long __functionAddress, int param0, long param1, long param2, int param3);
	public static native long invokeIPPP(long __functionAddress, int param0, long param1, long param2);
	public static native void invokeIPPPPIV(long __functionAddress, int param0, long param1, long param2, long param3, long param4, int param5);
	public static native void invokeIPPPV(long __functionAddress, int param0, long param1, long param2, long param3);
	public static native void invokeIPPV(long __functionAddress, int param0, long param1, long param2);
	public static native boolean invokeIPPZ(long __functionAddress, int param0, long param1, long param2);
	public static native void invokeIPPZV(long __functionAddress, int param0, long param1, long param2, boolean param3);
	public static native void invokeIPV(long __functionAddress, int param0, long param1);
	public static native boolean invokeIPZ(long __functionAddress, int param0, long param1);
	public static native short invokeIS(long __functionAddress, int param0);
	public static native void invokeISSSSV(long __functionAddress, int param0, short param1, short param2, short param3, short param4);
	public static native void invokeISSSV(long __functionAddress, int param0, short param1, short param2, short param3);
	public static native void invokeISSV(long __functionAddress, int param0, short param1, short param2);
	public static native void invokeISV(long __functionAddress, int param0, short param1);
	public static native void invokeIV(long __functionAddress, int param0);
	public static native boolean invokeIZ(long __functionAddress, int param0);
	public static native void invokeIZIIIPV(long __functionAddress, int param0, boolean param1, int param2, int param3, int param4, long param5);
	public static native void invokeIZIIPV(long __functionAddress, int param0, boolean param1, int param2, int param3, long param4);
	public static native void invokeIZV(long __functionAddress, int param0, boolean param1);
	public static native void invokeIZZZZV(long __functionAddress, int param0, boolean param1, boolean param2, boolean param3, boolean param4);
	public static native void invokeJIV(long __functionAddress, long param0, int param1);
	public static native void invokeJV(long __functionAddress, long param0);
	public static native boolean invokeJZ(long __functionAddress, long param0);
	public static native long invokeP(long __functionAddress);
	public static native int invokePFI(long __functionAddress, long param0, float param1);
	public static native int invokePI(long __functionAddress, long param0);
	public static native int invokePII(long __functionAddress, long param0, int param1);
	public static native int invokePIII(long __functionAddress, long param0, int param1, int param2);
	public static native int invokePIIIII(long __functionAddress, long param0, int param1, int param2, int param3, int param4);
	public static native int invokePIIIIIII(long __functionAddress, long param0, int param1, int param2, int param3, int param4, int param5, int param6);
	public static native void invokePIIIIIIIIIIV(long __functionAddress, long param0, int param1, int param2, int param3, int param4, int param5, int param6, int param7, int param8, int param9, int param10);
	public static native int invokePIIIIIIPIIIIIIIIII(long __functionAddress, long param0, int param1, int param2, int param3, int param4, int param5, int param6, long param7, int param8, int param9, int param10, int param11, int param12, int param13, int param14, int param15, int param16);
	public static native long invokePIIIP(long __functionAddress, long param0, int param1, int param2, int param3);
	public static native long invokePIIIPP(long __functionAddress, long param0, int param1, int param2, int param3, long param4);
	public static native int invokePIIIPPI(long __functionAddress, long param0, int param1, int param2, int param3, long param4, long param5);
	public static native boolean invokePIIIZ(long __functionAddress, long param0, int param1, int param2, int param3);
	public static native long invokePIIP(long __functionAddress, long param0, int param1, int param2);
	public static native int invokePIIPPPI(long __functionAddress, long param0, int param1, int param2, long param3, long param4, long param5);
	public static native void invokePIIPPV(long __functionAddress, long param0, int param1, int param2, long param3, long param4);
	public static native void invokePIIPV(long __functionAddress, long param0, int param1, int param2, long param3);
	public static native int invokePIJI(long __functionAddress, long param0, int param1, long param2);
	public static native int invokePIJPPIPPI(long __functionAddress, long param0, int param1, long param2, long param3, long param4, int param5, long param6, long param7);
	public static native void invokePIJV(long __functionAddress, long param0, int param1, long param2);
	public static native long invokePIP(long __functionAddress, long param0, int param1);
	public static native int invokePIPI(long __functionAddress, long param0, int param1, long param2);
	public static native int invokePIPIPIPPI(long __functionAddress, long param0, int param1, long param2, int param3, long param4, int param5, long param6, long param7);
	public static native int invokePIPIPPI(long __functionAddress, long param0, int param1, long param2, int param3, long param4, long param5);
	public static native int invokePIPJIPPI(long __functionAddress, long param0, int param1, long param2, long param3, int param4, long param5, long param6);
	public static native long invokePIPP(long __functionAddress, long param0, int param1, long param2);
	public static native int invokePIPPI(long __functionAddress, long param0, int param1, long param2, long param3);
	public static native long invokePIPPIPPPP(long __functionAddress, long param0, int param1, long param2, long param3, int param4, long param5, long param6, long param7);
	public static native int invokePIPPIPPPPI(long __functionAddress, long param0, int param1, long param2, long param3, int param4, long param5, long param6, long param7, long param8);
	public static native long invokePIPPP(long __functionAddress, long param0, int param1, long param2, long param3);
	public static native int invokePIPPPI(long __functionAddress, long param0, int param1, long param2, long param3, long param4);
	public static native int invokePIPPPIPPI(long __functionAddress, long param0, int param1, long param2, long param3, long param4, int param5, long param6, long param7);
	public static native long invokePIPPPP(long __functionAddress, long param0, int param1, long param2, long param3, long param4);
	public static native int invokePIPPPPI(long __functionAddress, long param0, int param1, long param2, long param3, long param4, long param5);
	public static native long invokePIPPPPP(long __functionAddress, long param0, int param1, long param2, long param3, long param4, long param5);
	public static native long invokePIPPPPPP(long __functionAddress, long param0, int param1, long param2, long param3, long param4, long param5, long param6);
	public static native void invokePIPPV(long __functionAddress, long param0, int param1, long param2, long param3);
	public static native void invokePIPV(long __functionAddress, long param0, int param1, long param2);
	public static native void invokePIV(long __functionAddress, long param0, int param1);
	public static native long invokePJIIIPP(long __functionAddress, long param0, long param1, int param2, int param3, int param4, long param5);
	public static native int invokePJIIPPI(long __functionAddress, long param0, long param1, int param2, int param3, long param4, long param5);
	public static native long invokePJIIPPP(long __functionAddress, long param0, long param1, int param2, int param3, long param4, long param5);
	public static native long invokePJIPP(long __functionAddress, long param0, long param1, int param2, long param3);
	public static native int invokePJIPPI(long __functionAddress, long param0, long param1, int param2, long param3, long param4);
	public static native long invokePJIPPP(long __functionAddress, long param0, long param1, int param2, long param3, long param4);
	public static native long invokePJPIP(long __functionAddress, long param0, long param1, long param2, int param3);
	public static native long invokePJPPPP(long __functionAddress, long param0, long param1, long param2, long param3, long param4);
	public static native long invokePJPPPPP(long __functionAddress, long param0, long param1, long param2, long param3, long param4, long param5);
	public static native long invokePJPPPPPPP(long __functionAddress, long param0, long param1, long param2, long param3, long param4, long param5, long param6, long param7);
	public static native long invokePJPPPPPPPPP(long __functionAddress, long param0, long param1, long param2, long param3, long param4, long param5, long param6, long param7, long param8, long param9);
	public static native long invokePP(long __functionAddress, long param0);
	public static native int invokePPFI(long __functionAddress, long param0, long param1, float param2);
	public static native int invokePPI(long __functionAddress, long param0, long param1);
	public static native int invokePPII(long __functionAddress, long param0, long param1, int param2);
	public static native void invokePPIIIIIIPIIIIIIIIIV(long __functionAddress, long param0, long param1, int param2, int param3, int param4, int param5, int param6, int param7, long param8, int param9, int param10, int param11, int param12, int param13, int param14, int param15, int param16, int param17);
	public static native long invokePPIIIP(long __functionAddress, long param0, long param1, int param2, int param3, int param4);
	public static native long invokePPIIPP(long __functionAddress, long param0, long param1, int param2, int param3, long param4);
	public static native int invokePPIIPPI(long __functionAddress, long param0, long param1, int param2, int param3, long param4, long param5);
	public static native int invokePPIJIPPI(long __functionAddress, long param0, long param1, int param2, long param3, int param4, long param5, long param6);
	public static native long invokePPIJPPIPPPP(long __functionAddress, long param0, long param1, int param2, long param3, long param4, long param5, int param6, long param7, long param8, long param9);
	public static native long invokePPIJPPPPIPPPP(long __functionAddress, long param0, long param1, int param2, long param3, long param4, long param5, long param6, long param7, int param8, long param9, long param10, long param11);
	public static native long invokePPIP(long __functionAddress, long param0, long param1, int param2);
	public static native int invokePPIPI(long __functionAddress, long param0, long param1, int param2, long param3);
	public static native long invokePPIPIP(long __functionAddress, long param0, long param1, int param2, long param3, int param4);
	public static native int invokePPIPPI(long __functionAddress, long param0, long param1, int param2, long param3, long param4);
	public static native int invokePPIPPPI(long __functionAddress, long param0, long param1, int param2, long param3, long param4, long param5);
	public static native int invokePPIPPPIPPI(long __functionAddress, long param0, long param1, int param2, long param3, long param4, long param5, int param6, long param7, long param8);
	public static native int invokePPIPPPPPIPPI(long __functionAddress, long param0, long param1, int param2, long param3, long param4, long param5, long param6, long param7, int param8, long param9, long param10);
	public static native int invokePPIPPPPPPPPIPPI(long __functionAddress, long param0, long param1, int param2, long param3, long param4, long param5, long param6, long param7, long param8, long param9, long param10, int param11, long param12, long param13);
	public static native void invokePPIPV(long __functionAddress, long param0, long param1, int param2, long param3);
	public static native void invokePPIV(long __functionAddress, long param0, long param1, int param2);
	public static native long invokePPJPP(long __functionAddress, long param0, long param1, long param2, long param3);
	public static native long invokePPP(long __functionAddress, long param0, long param1);
	public static native int invokePPPI(long __functionAddress, long param0, long param1, long param2);
	public static native void invokePPPIIPPPV(long __functionAddress, long param0, long param1, long param2, int param3, int param4, long param5, long param6, long param7);
	public static native long invokePPPIP(long __functionAddress, long param0, long param1, long param2, int param3);
	public static native long invokePPPIPP(long __functionAddress, long param0, long param1, long param2, int param3, long param4);
	public static native int invokePPPIPPI(long __functionAddress, long param0, long param1, long param2, int param3, long param4, long param5);
	public static native long invokePPPP(long __functionAddress, long param0, long param1, long param2);
	public static native int invokePPPPI(long __functionAddress, long param0, long param1, long param2, long param3);
	public static native int invokePPPPIPPIPPI(long __functionAddress, long param0, long param1, long param2, long param3, int param4, long param5, long param6, int param7, long param8, long param9);
	public static native void invokePPPPIV(long __functionAddress, long param0, long param1, long param2, long param3, int param4);
	public static native long invokePPPPP(long __functionAddress, long param0, long param1, long param2, long param3);
	public static native int invokePPPPPI(long __functionAddress, long param0, long param1, long param2, long param3, long param4);
	public static native int invokePPPPPIPPI(long __functionAddress, long param0, long param1, long param2, long param3, long param4, int param5, long param6, long param7);
	public static native int invokePPPPPPI(long __functionAddress, long param0, long param1, long param2, long param3, long param4, long param5);
	public static native int invokePPPPPPIPPI(long __functionAddress, long param0, long param1, long param2, long param3, long param4, long param5, int param6, long param7, long param8);
	public static native int invokePPPPPPPPPPIPPI(long __functionAddress, long param0, long param1, long param2, long param3, long param4, long param5, long param6, long param7, long param8, long param9, int param10, long param11, long param12);
	public static native void invokePPPPV(long __functionAddress, long param0, long param1, long param2, long param3);
	public static native void invokePPPV(long __functionAddress, long param0, long param1, long param2);
	public static native void invokePPV(long __functionAddress, long param0, long param1);
	public static native boolean invokePPZ(long __functionAddress, long param0, long param1);
	public static native void invokePV(long __functionAddress, long param0);
	public static native boolean invokePZ(long __functionAddress, long param0);
	public static native void invokeSSSSV(long __functionAddress, short param0, short param1, short param2, short param3);
	public static native void invokeSSSV(long __functionAddress, short param0, short param1, short param2);
	public static native void invokeSSV(long __functionAddress, short param0, short param1);
	public static native void invokeSV(long __functionAddress, short param0);
	public static native void invokeV(long __functionAddress);
	public static native void invokeZV(long __functionAddress, boolean param0);
	public static native void invokeZZZZV(long __functionAddress, boolean param0, boolean param1, boolean param2, boolean param3);

}
